### PR TITLE
Jg create tag 14

### PR DESCRIPTION
**Pull request by jeannettegeib**
# Description
[Ticket number 14](https://trello.com/c/wLX47r5h/14-14-create-a-tag) allows users to add a new tag by clicking on create from the tag management index. Note that a future ticket will limit this functionality to admin-only

#Updates included. 

- an  AddTag function was added to the TagRepository. 
- an AddTag function was added to the TagController. 
- an AddTag interface was added to the ITagRepository
- a Create.cshtml file was created in Views->Tag

# Testing Instructions

1. git add and git commit whatever you're working on on your branch
2. git checkout main
3.  git fetch --all
4.  git checkout **jg-AddTag-14**  to switch to my branch.
5.  If you don't see the most recent version of the files, try git pull origin jg-AddTag-14.
6.  Execute TabloidMVC from inside of Visual Studio
7.  If you haven't created the Tabloid MVC database, please do so.
8.  Use this to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-caramel-apple-pops/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
9.  Use this to seed the database: [SQL Seed Data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-caramel-apple-pops/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
10.  n browser, please go to Login on the nav bar and log in with this email: **admin@example.com**
11.  From the home page, select **Tag Management** from the nav bar. 
12.  From the index, click on "**Create New**"
13.  Add a word (any word, for example "Zaney" ) in the 'Name' field and click "Create'
14.  You should automatically be directed by to the index of tags. Find the word you added in the alphabetical list (If you added Zaney, it will be at the bottom of the list). If it is there, the feature works. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
Please provide more robust testing instructions. See document pinned in C6 channel called 'Pull Request Best Practices'

**Review by nthi — APPROVED** [review]
Pending changes requested by SCRUM master, approved.

I can navigate to Tag Management
I see a table of current tags with ID, name, and standard edit/details/delete links
I can click "Create New"
I can click in "Name" and enter a tag of my choice
I can click "Create"
When I click Create, I am returned to the Tag list and can see my new tag appears in the list.

**Comment by sarahebrooks12** [comment]
testing instructions look good! Please get 2 testing approvals before merging

**Review by julslt34 — APPROVED** [review]
I was able to go to Tag Management
There was a list of tags as mentioned and a create new link
I clicked Create New
I was able to add a new tag in the form
When I clicked create it rerouted me to the list and the new tag was there.
So works as stated.  Great Job!

**Pull request merged**
