### PR TITLE
Jg view all tags 13

### PR DESCRIPTION
**Pull request by jeannettegeib**
# Description
Ticket number 13 simply lists the available tags that have been added to the Tag table. Tags should be displayed in  alphabetical order. 
https://trello.com/c/NOqPFxpe

#Updates included. 

- a Tag model called Tag.cs was added to the Model folder. 
- a Tag interface called ITagRepository was added to the repositories folder with a get/set for a list of tags.
- a Tag Repository with a GetAll function was added to the Repositories folder. 
- a Tag Controller calling the GetAll function was added to the Controllers folder. 
- a Tag folder was created in the Views folder and an Index.cshtml was created
- the tag interface and repository were referenced in the ConfigureServices function in Startup.cs

# Testing Instructions

1.  `git add` and `git commit` whatever you're working on on your branch
2.  `git checkout main`
3. ` git fetch --a`
4.  `git checkout jg-ViewAllTags-13 ` to switch to my branch.
5. If you don't see the most recent version of the files, try` git pull origin jg-ViewAllTags-13`.
6. If you haven't created the Tabloid MVC database, please do so.
7.  Use this to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-caramel-apple-pops/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
8.  Use this to seed the database: [SQL Seed Data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-caramel-apple-pops/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
9. Execute TabloidMVC from inside of Visual Studio by clicking on the solid green arrow
10. In the browser, please log in. Seed data includes the login email **admin@example.com**
11.  From the home page, select Tag Management from the nav bar. 
12.  Observe if a list of tags (from seed data) is displayed and is in alphabetical order:

- C#
- Cyclopean Terrors
- Family 
- Javascript

 If so, the feature works.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by julslt34 — APPROVED** [review]
Looks good - It does exactly what it is supposed to.  Great Job!

**Review by nthi — APPROVED** [review]
I am able to navigate to Tag Management from the navbar and observe an alphabetical list of tags.

**Comment by sarahebrooks12** [comment]
Please provide more robust testing instructions. See document pinned in C6 channel called 'Pull Request Best Practices'

**Comment by sarahebrooks12** [comment]
testing instructions look good! Please get 2 testing approvals before merging

**Pull request merged**
